Sprint1
ClevertecFrontendLab/sprint1-Anastasiya1982 pull request #1
Opened 2023-01-27 15:22 UTC by Anastasiya1982

sprint 1

2023-01-28 12:13 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674908027/content-window.png)

2023-01-28 12:36 UTC, klichkovskiy requested changes

2023-01-28 12:36 UTC, klichkovskiy commented on src/index.js
> +          <Route path='/' element={<Layout />}>
Сделать адаптив. Приложение нормально работает только на 1440 и 768

2023-01-28 12:36 UTC, klichkovskiy commented on src/index.js
> +import './styles.scss';
Шрифты локально не подключаем!

2023-01-28 12:36 UTC, klichkovskiy commented on src/components/leftbar/leftbar.jsx
> +          <NavLink
![image](https://user-images.githubusercontent.com/62481116/215266487-868c0d39-23cc-4bc3-8967-b29d8db0a3a0.png)
Отступы сделать согласно макету

2023-01-28 12:36 UTC, klichkovskiy commented on src/categoreis.js
> +export const categories = [
Этот файл лучше хранить в папке constants

2023-01-28 12:36 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +        <div className='header-container'>
![image](https://user-images.githubusercontent.com/62481116/215266586-2466e653-2279-4f73-899d-f873ec230fbd.png)
Не по макету. Переделать.

2023-01-28 12:36 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +          <section className='detailed-information'>
![image](https://user-images.githubusercontent.com/62481116/215266604-c92bec3d-f983-4f30-8022-176144d09929.png)
Все поехало.

2023-01-28 12:36 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
> +              {usersRewiews.map((comment) => (
![image](https://user-images.githubusercontent.com/62481116/215266622-c798fa6e-39c1-40a6-a4c3-972197b6280c.png)
Сделать по макету

2023-01-28 12:36 UTC, klichkovskiy commented on src/index.js
> +              <Route path='/books/terms' element={<TermsPage />} />
Это две одинаковые страницы за исключением заголовка. Его можно передавать пропсом.

2023-01-28 15:43 UTC, Anastasiya1982 commented on src/index.js
> +import './styles.scss';
done

2023-01-28 15:50 UTC, Anastasiya1982 commented on src/components/leftbar/leftbar.jsx
> +          <NavLink
done

2023-01-28 15:51 UTC, Anastasiya1982 commented on src/categoreis.js
> +export const categories = [
done

2023-01-28 18:11 UTC, Anastasiya1982 commented on src/pages/book/book-page.jsx
> +        <div className='header-container'>
done

2023-01-28 18:12 UTC, Anastasiya1982 commented on src/pages/book/book-page.jsx
> +          <section className='detailed-information'>
done

2023-01-28 18:29 UTC, Anastasiya1982 commented on src/pages/book/book-page.jsx
> +              {usersRewiews.map((comment) => (
done

2023-01-28 18:44 UTC, Anastasiya1982 commented on src/index.js
> +              <Route path='/books/terms' element={<TermsPage />} />
done all changes

2023-01-28 18:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1674931708/content-window.png)

2023-01-28 18:58 UTC, klichkovskiy requested changes
Добавь отступы, отцентруй контент, убери скролы

2023-01-28 18:58 UTC, klichkovskiy commented on src/index.js
> +              <Route path='/books/terms' element={<TermsPage contentView='terms' />} />
Вот за это молодец!

2023-01-28 18:58 UTC, klichkovskiy commented on src/index.js
> +              <Route path='/books/' element={<Navigate to='all' />} />
![image](https://user-images.githubusercontent.com/62481116/215285596-1c2dfb1c-9ac7-40b1-8f1a-04b18911eeb9.png)
Где отступы?

2023-01-28 18:58 UTC, klichkovskiy commented on src/index.js
> +              <Route path='/books/' element={<Navigate to='all' />} />
![image](https://user-images.githubusercontent.com/62481116/215285624-1b2fe1ff-382a-4f34-b39a-6e30978f3a2a.png)
Тут вообще скролл

2023-01-28 18:58 UTC, klichkovskiy commented on src/index.js
> +              <Route path='/books/' element={<Navigate to='all' />} />
![image](https://user-images.githubusercontent.com/62481116/215285677-e0855eee-3bb0-465e-ab9b-a70b2268fda8.png)
А чего не отцентровать?

2023-01-28 18:58 UTC, klichkovskiy commented on src/index.js
> +              <Route path='/books/' element={<Navigate to='all' />} />
![image](https://user-images.githubusercontent.com/62481116/215285701-efe170ca-9ebc-46cc-a9f9-ccc126b117f0.png)
Где книга пропала?

2023-01-28 18:58 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
>  export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/215285798-18c1216a-a88a-4073-9b43-c70e308ae830.png)
Опять скрол

2023-01-28 18:58 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
>  export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/215285834-dfedfb25-d87d-43dd-ac85-fe52de5b6829.png)
Отступы, почему их нигде нет?

2023-01-28 18:58 UTC, klichkovskiy commented on src/pages/book/book-page.jsx
>  export const BookPage = () => {
![image](https://user-images.githubusercontent.com/62481116/215285872-3171f760-5089-4fbf-933a-b02590f74b5a.png)
И здесь скрол

2023-01-28 19:14 UTC, Anastasiya1982 commented on src/index.js
> +              <Route path='/books/terms' element={<TermsPage contentView='terms' />} />
спасибо)

2023-01-30 12:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 6.
Количество непройденных тестов: 0.
***
**book-page 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/book-page%20320px.png)
***
**book-page 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/book-page%20768px.png)
***
**book-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/book-page.png)
***
**content-list 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/content-list%20320px.png)
***
**content-list 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/content-list%20768px.png)
***
**content-list.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/content-list.png)
***
**content-window 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/content-window%20320px.png)
***
**content-window 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/content-window%20768px.png)
***
**content-window.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/Anastasiya1982/1675082897/content-window.png)

2023-01-30 12:52 UTC, klichkovskiy approved these changes

2023-01-30 17:49 UTC, merged